"""add session budget columns

Revision ID: 7c297c278ba6
Revises: 8ffb00ebefe1
Create Date: 2026-07-25 12:07:59.428008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c297c278ba6'
down_revision: Union[str, Sequence[str], None] = '8ffb00ebefe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('total_tokens_used', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('total_api_calls', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('max_api_calls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'max_api_calls')
    op.drop_column('game_sessions', 'total_api_calls')
    op.drop_column('game_sessions', 'total_tokens_used')
    # ### end Alembic commands ###
